### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shivonnu** [shivonnu/furima-29230#9]
# 自身のフリマアプリのURL
https://furima-29230.herokuapp.com/
# Basic認証のIDとパスワード
ID:admin パスワード:2222
# 出品者用のメールアドレスとパスワード
メールアドレス:nana@gmail.com パスワード:nanano123
# 購入者用のメールアドレスとパスワード
メールアドレス:nene@gmail.com パスワード:neneno123
 # 購入用カードの番号・期限・セキュリティコード
番号:5105105105105100 2月 25年　セキュリティーコード:123

**Comment by tcamp1234** [comment]
shivonnu さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

◎今回修正確認箇所にはありませんのでLGTMを出させて頂きましたが、出品者アカウントでのログインが出来ませんでしたのでご自身で修正しておくと宜しいかと思います。宜しくお願い致します！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by shivonnu** [comment]
ありがとうございます！出品者失礼しました、修正しました。以後気をつけます！
